services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  bot:
    image: ghcr.io/red-sight/weather-fit
    command: node dist/index.js
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - redis
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      REDIS_URL: redis://redis:6379

volumes:
  redis_data:
